stages:
  - build

variables:
  HOST_MOUNT: /eafdocs

build-docs:
  stage: build
  image: harbor.apps.okddev.fnal.gov/cache/library/python:3.12
  before_script:
    - pip install sphinx sphinx_rtd_theme
  script:
    - sphinx-build -b html docs/ build/
  artifacts:
    paths:
      - build/
    expire_in: 1 hour
  rules:
    - if: '$CI_COMMIT_BRANCH == "local-build"'
  tags:
    - eafdocs

publish-docs:
  stage: publish
  image: harbor.apps.okddev.fnal.gov/cache/library/python:3.12
  script:
    - cp -rf build/* $HOST_MOUNT
  tags:
    - eafdocs
  rules:
    - if: '$CI_COMMIT_BRANCH == "local-build"'
