#!/bin/bash
# nss_db_group - if we have nss_db configured for group via nsswitch.conf, 
# then confirm that the appropriate database exists and has entries.

NAME=nss_db_group
DB=/var/db/group.db
MINUTES=240

if egrep -q "^group:.*db" /etc/nsswitch.conf; then
    if [[ ! -f $DB ]]; then
        echo "2 $NAME - NOT OK - $DB does not exist"
        exit 1
    elif ! `getent -s db group > /dev/null`; then
        echo "2 $NAME - NOT OK - no entries in $DB"
        exit 2
    else
        echo "0 $NAME - OK - $DB exists and has entries"
        exit 0
    fi
else
    exit 0
fi
