#!/bin/bash
# confirm-json-fetchgroupdb - confirm that json-fetchgroupd is running 
# at least every couple of hours, and that it most recently succeeded.  

NAME=`basename $0`
LOG=/var/log/json-passwd.log
MINUTES=240

if ! egrep -q "^group:.*db" /etc/nsswitch.conf; then
    exit 0
fi

if [[ ! -f $LOG ]]; then
    echo "2 $NAME - NOT OK - $LOG not found (never ran?)"
    exit 2
fi

TIME=`stat -c '%Y' $LOG`
TIME2=$((`date +%s` - $TIME))
DIFF=`echo "$TIME2/60" | bc`

if [[ $DIFF -gt $MINUTES ]]; then
    echo "2 $NAME - NOT OK - $LOG >${MINUTES} minutes old (${DIFF}m)"
    exit 2
fi

LAST_ENTRY=`egrep group.db $LOG | egrep "SUCCESS|ERROR" | sort -r | head -1`
LE_SHORT=`echo $LAST_ENTRY | awk '{$1=""; print $0}' | sed -e s'/^\s\+//'`
if [[ $LAST_ENTRY =~ "SUCCESS" ]]; then
    echo "0 $NAME - OK - $LE_SHORT"
    exit 0
elif [[ $LAST_ENTRY =~ "ERROR" ]]; then
    echo "2 $NAME - NOT OK - $LE_SHORT"
    exit 0
else
    echo "2 $NAME - NOT OK - no last entry for group.db in $LOG"
    exit 2
fi
